services:
  app.url_manager:
    class: AppBundle\Service\UrlManager
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@app.url_parser"

  app.url_parser:
    class: League\Uri\UriParser

  app.serializer:
    class: AppBundle\Service\Serializer
    arguments:
      - "@jms_serializer.serializer"

  app.listener.serialization:
    class: AppBundle\Listener\SerializationListener
    arguments: ['@router']
    tags:
      - {name: jms_serializer.event_subscriber}

  app.listener.user.create:
    class: AppBundle\Listener\CreateUserListener
    arguments: ['@fos_user.object_manager']
    tags:
      - {name: kernel.event_listener, event: fos_user.user.created}
